/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetMomentCommentsReq struct {
	MomentId string `json:"moment_id,omitempty"`
	Userid string `json:"userid,omitempty"`
}
