/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MarkCorpContactTagReq struct {
	Userid string `json:"userid,omitempty"`
	ExternalUserid string `json:"external_userid,omitempty"`
	AddTag []string `json:"add_tag,omitempty"`
	RemoveTag []string `json:"remove_tag,omitempty"`
}
