/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// UpdateUserReq
type UpdateUserReq struct {
	Userid string `json:"userid,omitempty"`
	Name string `json:"name,omitempty"`
	Department []int32 `json:"department,omitempty"`
	Order []int32 `json:"order,omitempty"`
	Position string `json:"position,omitempty"`
	Mobile string `json:"mobile,omitempty"`
	Gender int32 `json:"gender,omitempty"`
	Email string `json:"email,omitempty"`
	IsLeaderInDept []int32 `json:"is_leader_in_dept,omitempty"`
	Enable int32 `json:"enable,omitempty"`
	AvatarMediaid string `json:"avatar_mediaid,omitempty"`
	Telephone string `json:"telephone,omitempty"`
	Alias string `json:"alias,omitempty"`
	Address string `json:"address,omitempty"`
	MainDepartment int32 `json:"main_department,omitempty"`
	Extattr *ExtAttrs `json:"extattr,omitempty"`
	ExternalPosition string `json:"external_position,omitempty"`
	ExternalProfile *ExternalProfile `json:"external_profile,omitempty"`
}
