/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// InviteReq
type InviteReq struct {
	User []string `json:"user,omitempty"`
	Party []string `json:"party,omitempty"`
	Tag []string `json:"tag,omitempty"`
}
