/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetGroupchatStatisticReq struct {
	DayBeginTime int32 `json:"day_begin_time,omitempty"`
	DayEndTime int32 `json:"day_end_time,omitempty"`
	OwnerFilter interface{} `json:"owner_filter,omitempty"`
	OrderBy int32 `json:"order_by,omitempty"`
	OrderAsc int32 `json:"order_asc,omitempty"`
	Offset int32 `json:"offset,omitempty"`
	Limit int32 `json:"limit,omitempty"`
}
