/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetGroupchatRspGroupChatItem struct {
	Userid string `json:"userid,omitempty"`
	Type_ int32 `json:"type,omitempty"`
	JoinTime int32 `json:"join_time,omitempty"`
	JoinScene int32 `json:"join_scene,omitempty"`
	Invitor *GetGroupchatRspGroupChatItemInvitor `json:"invitor,omitempty"`
	Unionid string `json:"unionid,omitempty"`
	Name string `json:"name,omitempty"`
	GroupNickname string `json:"group_nickname,omitempty"`
}
