/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FollowInfo struct {
	Userid string `json:"userid,omitempty"`
	Remark string `json:"remark,omitempty"`
	Description string `json:"description,omitempty"`
	Createtime int32 `json:"createtime,omitempty"`
	TagId []string `json:"tag_id,omitempty"`
	RemarkCorpName string `json:"remark_corp_name,omitempty"`
	RemarkMobiles []string `json:"remark_mobiles,omitempty"`
	OperUserid string `json:"oper_userid,omitempty"`
	AddWay string `json:"add_way,omitempty"`
	State string `json:"state,omitempty"`
}
