/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Department struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	NameEn string `json:"name_en,omitempty"`
	Parentid int32 `json:"parentid,omitempty"`
	Order int32 `json:"order,omitempty"`
}
