/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ContactDetailFollowUserTagItem struct {
	GroupName string `json:"group_name,omitempty"`
	TagName string `json:"tag_name,omitempty"`
	TagId string `json:"tag_id,omitempty"`
	Type_ int32 `json:"type,omitempty"`
}
