/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetGroupchatStatisticGroupByDayReq struct {
	DayBeginTime int32 `json:"day_begin_time,omitempty"`
	DayEndTime int32 `json:"day_end_time,omitempty"`
	OwnerFilter interface{} `json:"owner_filter,omitempty"`
}
