/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProfileMiniprogram struct {
	Type_ int32 `json:"type,omitempty"`
	Name string `json:"name,omitempty"`
	Miniprogram interface{} `json:"miniprogram,omitempty"`
}
