/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpdateContactWayReq struct {
	ConfigId string `json:"config_id,omitempty"`
	Remark string `json:"remark,omitempty"`
	SkipVerify bool `json:"skip_verify,omitempty"`
	Style int32 `json:"style,omitempty"`
	State string `json:"state,omitempty"`
	User []string `json:"user,omitempty"`
	Party []int32 `json:"party,omitempty"`
	// 临时会话二维码有效期，以秒为单位
	ExpiresIn int32 `json:"expires_in,omitempty"`
	ChatExpiresIn int32 `json:"chat_expires_in,omitempty"`
	Unionid string `json:"unionid,omitempty"`
	Conclusions interface{} `json:"conclusions,omitempty"`
}
