/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DelCorpTagReq struct {
	TagId []string `json:"tag_id,omitempty"`
	GroupId []string `json:"group_id,omitempty"`
	// 授权方安装的应用agentid。仅旧的第三方多应用套件需要填此参数
	Agentid string `json:"agentid,omitempty"`
}
