/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetServiceCorpTokenReq struct {
	// 授权方corpid
	AuthCorpid string `json:"auth_corpid,omitempty"`
	// 永久授权码，通过get_permanent_code获取
	PermanentCode string `json:"permanent_code,omitempty"`
}
