/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CorpTagGroup struct {
	GroupId string `json:"group_id,omitempty"`
	GroupName string `json:"group_name,omitempty"`
	CreateTime int32 `json:"create_time,omitempty"`
	Order int32 `json:"order,omitempty"`
	Deleted bool `json:"deleted,omitempty"`
	Tag []CorpTag `json:"tag,omitempty"`
}
