/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetServiceAuthInfoRsp struct {
	Errmsg string `json:"errmsg,omitempty"`
	Errcode int32 `json:"errcode,omitempty"`
	ExpiresIn int32 `json:"expires_in,omitempty"`
	PermanentCode string `json:"permanent_code,omitempty"`
	DealerCorpInfo interface{} `json:"dealer_corp_info,omitempty"`
	AuthInfo []interface{} `json:"auth_info,omitempty"`
}
