/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateAppchatReq struct {
	Name string `json:"name,omitempty"`
	Owner string `json:"owner,omitempty"`
	Chatid string `json:"chatid,omitempty"`
	Userlist []string `json:"userlist,omitempty"`
}
