/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetExternalContactBatchUserRsp struct {
	NextCursor string `json:"next_cursor,omitempty"`
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	ExternalContactList []interface{} `json:"external_contact_list,omitempty"`
}
