/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GroupchatListReq struct {
	// 客户群跟进状态过滤。0 - 所有列表(即不过滤);1 - 离职待继承;2 - 离职继承中;3 - 离职继承完成;默认为0
	StatusFilter int32 `json:"status_filter,omitempty"`
	OwnerFilter interface{} `json:"owner_filter,omitempty"`
	Cursor string `json:"cursor,omitempty"`
	Limit int32 `json:"limit,omitempty"`
}
