/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// CreateUserReq
type CreateUserReq struct {
	// 成员UserID。对应管理端的帐号，企业内必须唯一。不区分大小写，长度为1~64个字节。只能由数字、字母和“_-@.”四种字符组成，且第一个字符必须是数字或字母。
	Userid string `json:"userid,omitempty"`
	// 成员名称。长度为1~64个utf8字符
	Name string `json:"name,omitempty"`
	// 成员别名。长度1~32个utf8字符
	Alias string `json:"alias,omitempty"`
	// 手机号码。企业内必须唯一，mobile/email二者不能同时为空
	Mobile string `json:"mobile,omitempty"`
	// 成员所属部门id列表,不超过20个
	Department []int32 `json:"department,omitempty"`
	// 部门内的排序值
	Order []int32 `json:"order,omitempty"`
	// 职务信息
	Position string `json:"position,omitempty"`
	// 性别
	Gender int32 `json:"gender,omitempty"`
	// 邮箱
	Email string `json:"email,omitempty"`
	// 座机
	Telephone string `json:"telephone,omitempty"`
	// 个数必须和参数department的个数一致
	IsLeaderInDept int32 `json:"is_leader_in_dept,omitempty"`
	// 成员头像的mediaid
	AvatarMediaid string `json:"avatar_mediaid,omitempty"`
	// 启用/禁用成员。1表示启用成员，0表示禁用成员
	Enable int32 `json:"enable,omitempty"`
	// 自定义字段
	Extattr *ExtAttrs `json:"extattr,omitempty"`
}
