/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetGroupmsgListV2Req struct {
	ChatType string `json:"chat_type,omitempty"`
	StartTime int32 `json:"start_time,omitempty"`
	EndTime int32 `json:"end_time,omitempty"`
	Creator string `json:"creator,omitempty"`
	// 创建人类型。0：企业发表 1：个人发表 2：所有，包括个人创建以及企业创建，默认情况下为所有类型
	FilterType int32 `json:"filter_type,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
