/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetGroupchatStatisticRsp struct {
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	Total int32 `json:"total,omitempty"`
	NextOffset int32 `json:"next_offset,omitempty"`
	Items []interface{} `json:"items,omitempty"`
}
