/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MpArticleMsg struct {
	Title string `json:"title,omitempty"`
	ThumbMediaId string `json:"thumb_media_id,omitempty"`
	Author string `json:"author,omitempty"`
	ContentSourceUrl string `json:"content_source_url,omitempty"`
	Content string `json:"content,omitempty"`
	Digest string `json:"digest,omitempty"`
}
