/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VideoMsg struct {
	MediaId string `json:"media_id,omitempty"`
	Title string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
}
