/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpdateTaskcardReq struct {
	Userid []string `json:"userid,omitempty"`
	Agentid int32 `json:"agentid,omitempty"`
	TaskId string `json:"task_id,omitempty"`
	ReplaceName string `json:"replace_name,omitempty"`
}
