/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TagListInfo struct {
	Tagid int32 `json:"tagid,omitempty"`
	Tagname string `json:"tagname,omitempty"`
}
