/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpdateExternalContactRemarkReq struct {
	Userid string `json:"userid,omitempty"`
	ExternalUserid string `json:"external_userid,omitempty"`
	Remark string `json:"remark,omitempty"`
	Description string `json:"description,omitempty"`
	RemarkCompany string `json:"remark_company,omitempty"`
	RemarkMobiles []string `json:"remark_mobiles,omitempty"`
	RemarkPicMediaid string `json:"remark_pic_mediaid,omitempty"`
}
