/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetUserBehaviorDataReq struct {
	Userid []string `json:"userid,omitempty"`
	Partyid []int32 `json:"partyid,omitempty"`
	StartTime int32 `json:"start_time,omitempty"`
	EndTime int32 `json:"end_time,omitempty"`
}
