/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetServicePreAuthCodeRsp struct {
	Errmsg string `json:"errmsg,omitempty"`
	Errcode int32 `json:"errcode,omitempty"`
	PreAuthCode string `json:"pre_auth_code,omitempty"`
	ExpiresIn int32 `json:"expires_in,omitempty"`
}
