/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddMsgTemplateReq struct {
	ChatType string `json:"chat_type,omitempty"`
	ExternalUserid []string `json:"external_userid,omitempty"`
	Sender string `json:"sender,omitempty"`
	Text interface{} `json:"text,omitempty"`
	Attachments []interface{} `json:"attachments,omitempty"`
}
