/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetAgentRsp struct {
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	Agentid int32 `json:"agentid,omitempty"`
	Name string `json:"name,omitempty"`
	SquareLogoUrl string `json:"square_logo_url,omitempty"`
	Description string `json:"description,omitempty"`
	Close int32 `json:"close,omitempty"`
	RedirectDomain string `json:"redirect_domain,omitempty"`
	ReportLocationFlag int32 `json:"report_location_flag,omitempty"`
	Isreportenter int32 `json:"isreportenter,omitempty"`
	HomeUrl string `json:"home_url,omitempty"`
	AllowUserinfos interface{} `json:"allow_userinfos,omitempty"`
	AllowPartys interface{} `json:"allow_partys,omitempty"`
	AllowTags interface{} `json:"allow_tags,omitempty"`
}
