/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddGroupWelcomeTemplateReq struct {
	Text interface{} `json:"text,omitempty"`
	Image interface{} `json:"image,omitempty"`
	Link interface{} `json:"link,omitempty"`
	Miniprogram interface{} `json:"miniprogram,omitempty"`
	// 授权方安装的应用agentid。仅旧的第三方多应用套件需要填此参数
	Agentid int32 `json:"agentid,omitempty"`
	// 是否通知成员将这条入群欢迎语应用到客户群中，0-不通知，1-通知， 不填则通知
	Notify int32 `json:"notify,omitempty"`
}
