/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetUnassignedListRsp struct {
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	IsLast bool `json:"is_last,omitempty"`
	NextCursor string `json:"next_cursor,omitempty"`
	Info []interface{} `json:"info,omitempty"`
}
