/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetGroupmsgTaskReq struct {
	Msgid string `json:"msgid,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
