/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateDepartmentReq struct {
	// 部门名称。同一个层级的部门名称不能重复。长度限制为1~32个字符，字符不能包括\\:?”<>｜
	Name string `json:"name,omitempty"`
	NameEn string `json:"name_en,omitempty"`
	Parentid int32 `json:"parentid,omitempty"`
	Order int32 `json:"order,omitempty"`
	// 部门id，32位整型，指定时必须大于1。若不填该参数，将自动生成id
	Id int32 `json:"id,omitempty"`
}
