/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EditCorpTagReq struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Order string `json:"order,omitempty"`
	Agentid int32 `json:"agentid,omitempty"`
}
