/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetGroupchatRspGroupChat struct {
	ChatId string `json:"chat_id,omitempty"`
	Name string `json:"name,omitempty"`
	Owner string `json:"owner,omitempty"`
	Notice string `json:"notice,omitempty"`
	CreateTime int32 `json:"create_time,omitempty"`
	MemberList []GetGroupchatRspGroupChatItem `json:"member_list,omitempty"`
	AdminList []GetGroupchatRspGroupChatAdminList `json:"admin_list,omitempty"`
}
