/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Btn struct {
	Key string `json:"key,omitempty"`
	Name string `json:"name,omitempty"`
	ReplaceName string `json:"replace_name,omitempty"`
	Color string `json:"color,omitempty"`
	IsBold bool `json:"is_bold,omitempty"`
}
