/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// User
type GetUserRsp struct {
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	// 成员UserID。对应管理端的帐号，企业内必须唯一。不区分大小写，长度为1~64个字节。只能由数字、字母和“_-@.”四种字符组成，且第一个字符必须是数字或字母。
	Userid string `json:"userid,omitempty"`
	// 成员名称。长度为1~64个utf8字符
	Name string `json:"name,omitempty"`
	// 成员所属部门id列表,不超过20个
	Department []int32 `json:"department,omitempty"`
	// 部门内的排序值
	Order []int32 `json:"order,omitempty"`
	// 职务信息
	Position string `json:"position,omitempty"`
	// 手机号码。企业内必须唯一，mobile/email二者不能同时为空
	Mobile string `json:"mobile,omitempty"`
	// 性别
	Gender int32 `json:"gender,omitempty"`
	// 邮箱
	Email string `json:"email,omitempty"`
	// 个数必须和参数department的个数一致
	IsLeaderInDept int32 `json:"is_leader_in_dept,omitempty"`
	// 成员头像的mediaid
	Avatar string `json:"avatar,omitempty"`
	// 头像缩略图url
	ThumbAvatar string `json:"thumb_avatar,omitempty"`
	// 座机
	Telephone string `json:"telephone,omitempty"`
	// 成员别名。长度1~32个utf8字符
	Alias string `json:"alias,omitempty"`
	// 地址
	Address string `json:"address,omitempty"`
	// 全局唯一。对于同一个服务商，不同应用获取到企业内同一个成员的open_userid是相同的，最多64个字节。仅第三方应用可获取
	OpenUserid string `json:"open_userid,omitempty"`
	// 主部门
	MainDepartment string `json:"main_department,omitempty"`
	// 激活状态 1=已激活，2=已禁用，4=未激活，5=退出企业。
	Status int32 `json:"status,omitempty"`
	// 员工个人二维码，扫描可添加为外部联系人(注意返回的是一个url，可在浏览器上打开该url以展示二维码)；第三方仅通讯录应用可获取。
	QrCode string `json:"qr_code,omitempty"`
	// 对外职务
	ExternalPosition string `json:"external_position,omitempty"`
	// 成员对外属性
	ExternalProfile *ExternalProfile `json:"external_profile,omitempty"`
	// 自定义字段
	Extattr *ExtAttrs `json:"extattr,omitempty"`
}
