/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SendWelcomeMsgReq struct {
	WelcomeCode string `json:"welcome_code,omitempty"`
	Text interface{} `json:"text,omitempty"`
	Attachments []interface{} `json:"attachments,omitempty"`
}
