/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LinkedcorpUserInfoAttrWeb struct {
	Name string `json:"name,omitempty"`
	Type_ int32 `json:"type,omitempty"`
	Web interface{} `json:"web,omitempty"`
}
