/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetExternalContactBatchUserReq struct {
	UseridList []string `json:"userid_list,omitempty"`
	Cursor string `json:"cursor,omitempty"`
	Limit int32 `json:"limit,omitempty"`
}
