/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SetAgentReq struct {
	Agentid int32 `json:"agentid,omitempty"`
	ReportLocationFlag int32 `json:"report_location_flag,omitempty"`
	LogoMediaid string `json:"logo_mediaid,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	RedirectDomain string `json:"redirect_domain,omitempty"`
	Isreportenter int32 `json:"isreportenter,omitempty"`
	HomeUrl string `json:"home_url,omitempty"`
}
