/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MediaUploadRsp struct {
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	Type_ string `json:"type,omitempty"`
	MediaId string `json:"media_id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}
