/*
 * 企业微信服务端API
 *
 * 企业微信服务端API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetGroupchatReq struct {
	ChatId string `json:"chat_id,omitempty"`
	NeedName int32 `json:"need_name,omitempty"`
}
